-- Shadow verdicts (Oct 2026): every verdict the engine reaches on a ticket — taken,
-- skipped, passed or blocked — with what it saw and, once its expiry has passed, what
-- the trade would have made. The evidence base for calibrating gates and scores:
-- a blocker earns its place only if what it blocks loses money.
create table if not exists options.shadow_verdicts (
  id              bigint generated by default as identity primary key,
  sig             text not null unique,          -- session date | engine | underlying | strategy | legs | expiry
  account         text,
  engine          text not null,                 -- 0DTE | 45DTE
  session_date    text not null,                 -- YYYY-MM-DD (New York session)
  first_seen      timestamptz not null default now(),
  last_seen       timestamptz not null default now(),
  underlying      text not null,
  strategy        text,
  legs            jsonb not null,                -- [{ strike, right: 'C'|'P', qty: signed }]
  expiry          text not null,                 -- YYYYMMDD
  spot            numeric,
  category        text not null,                 -- taken | trade | pass | blocked | unsized
  verdict         text,                          -- the headline the ticket showed
  blockers        text,
  edge_score      numeric,
  ev              numeric,
  kelly_usd       numeric,
  contracts       integer,
  entry_net       numeric,                       -- per share, + credit / − debit
  entry_source    text,                          -- ticket | model
  win             numeric,
  risk            numeric,
  pop             numeric,
  p_max_loss      numeric,
  move_cost       numeric,
  inputs          jsonb,                         -- market snapshot the verdict was built from
  decision_ts     text,                          -- Decisions timestamp when taken
  settle_date     text,
  settle_price    numeric,
  pnl_per_ct      numeric,                       -- held to expiry, from entry_net, before commission
  settle_source   text,
  settled_at      timestamptz
);
create index if not exists shadow_verdicts_unsettled_idx on options.shadow_verdicts (expiry) where settled_at is null;
create index if not exists shadow_verdicts_account_idx on options.shadow_verdicts (account, session_date);
alter table options.shadow_verdicts enable row level security;
