-- Working orders and entry fills (Oct 2026).
--
-- Until now a logged trade was assumed filled the moment it was logged. In practice
-- a 45DTE multi-leg order rests — sometimes all day, sometimes never — and with size
-- it arrives in pieces at different prices. Two things were therefore unrecordable:
-- whether an order filled at all, and how the price you got compared with the price
-- you asked for.
--
-- `fills` is the entry-side mirror of `closes`: one row per partial entry fill, so
-- 5 contracts arriving as 2 then 3 is recorded as two rows rather than flattened to
-- an average. The decision row carries what was ASKED (the limit, when it was sent);
-- the fills carry what was GOT.

create table if not exists options.fills (
  row_no         bigint generated by default as identity primary key,
  fill_id        text not null,
  ticket_ref     bigint not null,
  ticket_timestamp text,
  engine         text,
  underlying     text,
  strategy       text,
  -- NY session date of the fill, not the calendar date of the machine.
  fill_date      text,
  fill_time      text,
  qty_filled     numeric,
  qty_remaining  numeric,
  -- Signed like net_debit_credit elsewhere: negative is a debit paid, positive a
  -- credit received, per contract.
  fill_price     numeric,
  -- What was asked for at the moment this piece was sent. Kept per fill, not only
  -- on the ticket: a working order that is re-priced while it rests has more than
  -- one limit, and comparing a later fill against the original would flatter it.
  limit_price    numeric,
  -- Combo mid when the order was sent, if the bridge knew it. The honest baseline
  -- for slippage: the limit is a choice, the mid is the market.
  mid_at_send    numeric,
  fees_usd       numeric,
  order_ref      text,
  account        text,
  notes          text,
  created_at     timestamptz not null default now()
);

create unique index if not exists fills_fill_id_key on options.fills (fill_id);
create index if not exists fills_ticket_ref_idx on options.fills (ticket_ref);

-- What the ticket asked for, and when it started asking.
alter table options.decisions
  add column if not exists limit_price text,
  add column if not exists order_ref text,
  add column if not exists working_since text;

-- The trade log grows an entry side to match its exit side.
alter table options.trade_log
  add column if not exists limit_price text,
  add column if not exists qty_filled text,
  add column if not exists avg_entry text,
  add column if not exists entry_slippage text;

grant select, insert, update, delete on options.fills to options_app;
grant usage, select on sequence options.fills_row_no_seq to options_app;

-- Same shape as every other options table: RLS on with one policy for the app role,
-- so a new table is never the one that is quietly readable by something else.
alter table options.fills enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policy p
    join pg_class c on c.oid = p.polrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'options' and c.relname = 'fills' and p.polname = 'app_all'
  ) then
    create policy app_all on options.fills for all to options_app using (true) with check (true);
  end if;
end $$;
